### ISSUE TITLE
WarningCircle, Warning and Info don't change color correctly

### ISSUE THREAD

**Issue by dohomi** [mwood23/tamagui-phosphor-icons#1]
Hi

thanks for your package, I just tried it out in my package. I found out that Info, Warning and some more icons when used with `color` prop doesn't colorise correctly

See the screenshot attached
<img width="251" alt="Screenshot 2023-01-19 at 14 27 29" src="https://user-images.githubusercontent.com/489221/213371129-2b5270ed-529c-432f-9a09-8a1946bf5d52.png">

**Comment by mwood23** [comment]
Thanks for the report! I bet I missed one spot on the generate script. I'll try to look into it this week

**Comment by mwood23** [comment]
@dohomi Just pushed 0.1.3. Could you see if that fixed it? Not sure what how duotones will do with the updates so if you see anything let me know!

**Comment by dohomi** [comment]
@mwood23 I updated to the latest release but the issue is still present: 

https://tamagui-extras.vercel.app/?path=/story/ui-content-alert--error

You can see the usage here:
https://github.com/dohomi/tamagui-kitchen-sink/blob/master/packages/ui/src/components/content/LmAlert.tsx#L35

**Comment by mwood23** [comment]
I fixed it and pushed a release without building lol. Fixed in 0.1.4. Also, please check out the reason to make sure your next.config.js config is optimized for a big perf boost! Going to close, thanks for opening!

**Comment by dohomi** [comment]
@mwood23 thanks for working on it! And yes I realised the perf issues on NextJS as well, now I don't need to open a new PR :-)
