### ISSUE TITLE
phosphor icons break in Storybook environment

### ISSUE THREAD

**Issue by dohomi** [mwood23/tamagui-phosphor-icons#3]
I have created a simple Checkbox component which used in the past `@tamagui/lucide-icons`. The two icons used I swop to `tamagui-phosphor-icons`. From now onwards the component is broken with following error:
```
Uncaught Error: No parent manager given
``` 
You can see the component an repo here:  https://github.com/dohomi/tamagui-kitchen-sink/blob/master/packages/ui/src/components/forms/LmCheckbox.tsx#L13

**Comment by mwood23** [comment]
I think this is a problem with your storybook config. The tamagui provider needs to go above the context for phosphor. 

```
Uncaught Error: No parent manager given
```

This usually means the tamagui provider is not wrapping. In storybook you'll need to configure the provider to wrap all of your stories.

**Comment by dohomi** [comment]
@mwood23 the provider in Storybook is set. There is a mismatch of `@tamagui/core` in my environment, after setting 
```
resolutions: { "@tamagui/core": "1.1.5"}
```
Storybook works as expected. I think its ideal to move to peerDepenedencies I created a PR which solves this issue #4

**Comment by mwood23** [comment]
Closing from PR. Thanks again!
